#ifndef OFFICIAL_GLOW_H
#define OFFICIAL_GLOW_H
#include "types.h"
#define OFFICIAL_GLOW_BASE    0x23000000u
#define OFFICIAL_GLOW_MAGIC   0x32474C47u /* "GLG2" */
#define OFFICIAL_GLOW_A_COUNT 60u
#define OFFICIAL_GLOW_B_COUNT 30u
#define OFFICIAL_GLOW_F_COUNT 45u
#define OFFICIAL_GLOW_COUNT   (OFFICIAL_GLOW_A_COUNT+OFFICIAL_GLOW_B_COUNT+OFFICIAL_GLOW_F_COUNT)
#define OFFICIAL_GLOW_HALF_W  200u
#define OFFICIAL_GLOW_HALF_H  120u
#endif
